### ISSUE TITLE
problems with the library

### ISSUE THREAD

**Issue by Moreddu** [neuronetio/react-gantt-schedule-timeline-calendar#1]
hello, i would like to understand why your software library fails when used with react. i use the wrapper as in the example but there are errors, for example in the `return <div ref={callback} />;` of the GSTC.js file. moreover, if it is not commented, `useeffect()` is not defined.

**Comment by neuronetio** [comment]
try to update your react version

**Comment by Moreddu** [comment]
There is always the problem of return `<div ref={callback} />;` . The React version is 16.12. I created a new react project from scratch but it always gives me the same problem.

**Comment by neuronetio** [comment]
ok, I will check it out

**Comment by neuronetio** [comment]
Everything works for me hmmm
try to clone this whole repo and run `npm run start`
maybe there is something in your configuration/stack I don't know

paste error screenshot here

**Comment by neuronetio** [comment]
oh no sorry, I have the same problem
![image](https://user-images.githubusercontent.com/25027696/73566859-3cc2b380-4465-11ea-90e7-8baefa52bf51.png)

**Comment by neuronetio** [comment]
fixed in v1.1.19

Thanks for report!
