### ISSUE TITLE
Typescript: Could not find a declaration file for module

### ISSUE THREAD

**Issue by edouard-lopez** [neuronetio/react-gantt-schedule-timeline-calendar#12]
**related:** #11 

---

I'm using the component with a `create-react-app` based project and run my test with `jest` and `@testing-library/react`.

When import the library in a `.tsx` file:

	import GSTC from "react-gantt-schedule-timeline-calendar";

I got the error below:

```
Could not find a declaration file for module 'react-gantt-schedule-timeline-calendar'. '/data/projects/contribute/coronavirus-policies-timeline/node_modules/react-gantt-schedule-timeline-calendar/dist/GSTC.js' implicitly has an 'any' type.
  Try `npm install @types/react-gantt-schedule-timeline-calendar` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-gantt-schedule-timeline-calendar';`
```

The `@types/…` package is non-existent:
```
❯ yarn add --dev @types/react-gantt-schedule-timeline-calendar
error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2freact-gantt-schedule-timeline-calendar: Not found".
```

**Comment by edouard-lopez** [comment]
Fixed by replacing `import` by `require`

```diff
-import GSTC from "react-gantt-schedule-timeline-calendar";
+const GSTC = require("react-gantt-schedule-timeline-calendar");
```

as well as creating a file `src/types/react-gantt-schedule-timeline-calendar.d.ts` with following content:

	declare module 'react-gantt-schedule-timeline-calendar'

**Comment by edouard-lopez** [comment]
Still one issue on typing:

      subs.forEach((unsub) => unsub())

**Comment by neuronetio** [comment]
This is js version so no types will be created for this particular repo.
Original version of gantt-schedule-timeline-calendar has types, maybe it will help a little.
