### ISSUE TITLE
how to set initial display to today's position

### ISSUE THREAD

**Issue by tkymr827** [neuronetio/react-gantt-schedule-timeline-calendar#14]
by default it starts with the oldest items
but I want to have today in the middle in the initial state
please tell me, thank you

**Comment by T4SUYA** [comment]
Hello, you can achieve this with something like this: `var date = new Date()
    date.setHours(0, 0, 0, 0)
    var today = date.getTime()
    gstcInstance.api.scrollToTime(today)`

**Comment by tkymr827** [comment]
@T4SUYA 
im sorry to reply late, but I was able to get it done! 
thank you so much
