### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by matheusmorett2** [neuronetio/react-gantt-schedule-timeline-calendar#15]
## Error when start the project

Im getting this error when i try to start the project

<img width="1296" alt="Screen Shot 2020-09-25 at 00 56 21" src="https://user-images.githubusercontent.com/24697383/94224916-093c0a00-feca-11ea-9b4d-51cd5a108eae.png">

## Steps to reproduce

1. git clone
2. put the credentials
3. yarn
4. yarn start

**Comment by neuronetio** [comment]
should be fixed in `3.0.3`
