### ISSUE TITLE
Destroy chart on useEffect

### ISSUE THREAD

**Issue by ServicedeskZenabis** [neuronetio/react-gantt-schedule-timeline-calendar#7]
I'm trying to understand the reason the components is being destroyed on useEffect function, it seems I cant do any updates when using it on my ReactJS.

https://github.com/neuronetio/react-gantt-schedule-timeline-calendar/blob/0246a62df33ab9747e77055d9840d08092a03e9a/src/components/GSTC.js#L27

**Comment by MisterAJ** [comment]
I'm having this issue as well, did you find a workaround @ServicedeskZenabis ?

**Comment by neuronetio** [comment]
because it is a cleanup function?
https://reactjs.org/docs/hooks-reference.html#cleaning-up-an-effect

> The clean-up function runs before the component is removed from the UI to prevent memory leaks.
