### ISSUE TITLE
How to use in Laravel?

### ISSUE THREAD

**Issue by MrFrytaPL** [neuronetio/react-gantt-schedule-timeline-calendar#9]
Hi, I tried to use it in Laravel, I executed npm i react-gantt-schedule-timeline-calendar
I copy-pase examples like index.js etc. into my project, but it doesn't work. Some files is missing, probably npm installed the package in different directories OR I don't know what am I supposted to do to use your code.
How to start working on Laravel?
(I've got configured React in Laravel - simple components works)

**Comment by neuronetio** [comment]
I'am not up to date with laravel so I cannot help.
Maybe try to link to dist forlder? I don't know.
